### ISSUE TITLE
Why no ApplicativeSeq for Task?

### ISSUE THREAD

**Issue by cryptogohan** [nullpub/fun#11]
Am I missing something?

Sometimes when traversing you'd like it done sequentially, in my case because of rate-limiting reasons. TaskEither has an ApplicativeSeq, why not Task?

**Comment by baetheus** [comment]
There is a Sequential Apply for Task [here](https://github.com/nullpub/fun/blob/main/task.ts#L85). The only difference between apply and applicative is the of constructor. I can see how you'd need the Applicative module for traverse and should be able to implement it this weekend. I'd also welcome a PR if you're up to it. Unfortunately, Deno 1.10 generates better coverage reports (that show functional missing some branches in testing) so I was hoping to fix that first. Anyway, thanks for the find!

**Comment by cryptogohan** [comment]
I quickly whippped up:
```ts
import { ApplySeq } from "https://deno.land/x/fun@v1.0.0/task.ts";
import type * as TC from "https://deno.land/x/fun@v1.0.0/type_classes.ts";

const URI = "Task";
type URI = typeof URI;
const Functor: TC.Functor<URI> = {
  map: (fab) => (ta) => () => ta().then(fab),
};
export const ApplicativeSeq: TC.Applicative<URI> = {
  of: (a) => () => Promise.resolve(a),
  ap: ApplySeq.ap,
  map: Functor.map,
};
```

But then didn't end up testing or actually even using it haha 😅 .

I'm a bit tight on time right now. Next time I need it, if it isn't there, I'm happy to take a shot.

**Comment by baetheus** [comment]
Yeah, I'd do basically the same thing:

```ts
import type * as TC from "https://deno.land/x/fun@v1.0.0/type_classes.ts";
import * as T from "https://deno.land/x/fun@v1.0.0/task.ts";

const ApplicativeSeq: TC.Applicative<T.URI> = {
  of: T.of,
  ap: ApplySeq.ap,
  map: T.map,
}
```
