### ISSUE TITLE
Feature: Branded types like newtype-ts

### ISSUE THREAD

**Issue by cryptogohan** [nullpub/fun#15]
Let me start by asking, is there interest in them, and if so is this library the place?

I currently have an example of wanting to brand a iso datetime string:
```ts
/** ISO 8601 Datetime string */
type DateTimeString = string;

const dateTimeString: D.Decoder<DateTimeString> = (i: unknown) =>
  G.string(i) && !Number.isNaN(new Date(i))
    ? D.success(i)
    : D.failure(i, "not a parseable date");

const UserV2 = D.struct({
  accountCreatedAt: dateTimeString,
  bio: D.string,
  firstSeen: D.number,
  followedByUsm: D.boolean,
  followersCount: D.number,
  followingCount: D.number,
  handle: D.string,
  lastSeen: D.number,
  name: D.string,
  partOfFamList: D.boolean,
  profileImageUrl: D.string,
  tweetCount: D.number,
  twitterId: D.string,
});

type UserV2 = D.TypeOf<typeof UserV2>;
```

This is something but unlike branded types or newtypes the type engine doesn't actually do anything to help you make sure you're not working with a random string, apart from this decoder trying to ensure this is the case at runtime.

Does someone have a way they're handling this now in their Deno code? If no one does, is there a need? And if there's a need, should we fulfill it with this library? (:

**Comment by cryptogohan** [comment]
Hmmm, seems with an implementation for `refine` this would already be possible: https://github.com/gcanti/io-ts/blob/master/Schema.md

**Comment by cryptogohan** [comment]
Trying this now:
```ts
export interface DateTimeStringBrand {
  readonly DateTimeString: unique symbol;
}

/** ISO 8601 Datetime string */
export type DateTimeString = string & DateTimeStringBrand;

const guardIsDateTimeString = (i: unknown): i is DateTimeString =>
  G.string(i) && !Number.isNaN(new Date(i));

export const dateTimeString: D.Decoder<DateTimeString> = (i: unknown) =>
  guardIsDateTimeString(i) ? D.success(i) : D.failure(i, "a parseable date");
```

**Comment by baetheus** [comment]
I pulled a lot out of the Schemable implementations to get them tested and working well. I'm definitely interested in Branded types as well, but I had to put a limit on the number of things I wanted to initially port to functional. I think there are two improvements that need to be made to get the work you're doing to be easier:

1. Extend Decoder to have an input type instead of just unknown.
2. Port [newtype-ts](https://gcanti.github.io/newtype-ts/) either inside fun or as another project. (Thoughts on this are welcome)

**Comment by baetheus** [comment]
The Schemable section of this library is going to get an overhaul as well.

**Comment by baetheus** [comment]
@alextes The overhaul of Schemable and specifically [Decoder](https://github.com/nullpub/fun/blob/main/schemable/decoder.ts) was landed in main recently. Take a look and let me know what you think. Here is a simple implementation of the type you were looking for in the original issue. It doesn't use branded types but it does refine to the Date type.

```ts
import * as D from "../schemable/decoder.ts";
import * as R from "../schemable/result.ts";
import { flow } from "../fns.ts";

export const test: D.Decoder<unknown, Date> = flow(
  D.union(D.string)(D.number),
  R.chain((s) => {
    const result = new Date(s);
    return isNaN(result.getTime())
      ? D.failure(s, "parsable date as number or string")
      : D.success(result);
  }),
);
```

**Comment by baetheus** [comment]
@alextes I just landed a minimal implementation of [Newtype](https://github.com/nullpub/fun/blob/main/newtype.ts) in main. With that you should be able to use newtypes in your decoders. I would still recommend decoding to an actual Date in this case, but the option is now available. In addition I implemented `refine` in Decoder as well, so you can more easily implement refinements to branded types.

**Comment by alextes** [comment]
@baetheus neat! Regrettably, I'm mostly working with NodeJS again. Too many issues on the database driver side :( . 

This lib worked great!

**Comment by baetheus** [comment]
@alextes That makes sense, I'm hoping to build up to a streaming parser lib in the next year, for which some of the more simplistic db protocols (read: redis) should be easier to implement. It'll be interesting if I ever get to it. Anyway, take care!
