### ISSUE TITLE
How to combine five TaskEither?

### ISSUE THREAD

**Issue by cryptogohan** [nullpub/fun#16]
Say you have five TaskEither's. Four share the same Left error, one has its own. All five results need to go into a single response so you'd like to bind / map them into the same context.

I tried Do but it only allows binding three. How would you get five TaskEither results into the same function?

**Comment by baetheus** [comment]
Probably `sequenceTuple` or `sequenceStruct` would be my method. However, it looks like I didn't implement those helpers for TaskEither. Here is how you can do that yourself until I get them merged:

```ts
import * as TE from "../task_either.ts";
import * as S from "../sequence.ts";

const sequenceStruct = S.createSequenceStruct(TE.Apply);

const one = TE.right<number, number>(1);
const two = TE.right<number, number>(2);
const three = TE.right<number, number>(3);
const four = TE.right<number, number>(4);
const five = TE.right<string, number>(5);

// TaskEither<string | number, { one: number, two: number, three: number, four: number, five: number }>
const combined = sequenceStruct({
  one,
  two,
  three,
  four,
  five,
});
```

I won't have much time this month to work on functional but starting in July my schedule opens up and I'll be able to come back and get a lot of these tickets done.

**Comment by cryptogohan** [comment]
Awesome, thanks @baetheus . No worries about the unavailability, fine by me to slowly polish the gem you've made. I'll open PRs if I get impatient 😉 .

**Comment by baetheus** [comment]
Keep in mind that there are two implementations of the `Apply` type class for `TaskEither`. The default export (just `Apply`) is parallel, while the `ApplySeq` export is sequential.

**Comment by baetheus** [comment]
Since the issue here has been answered I'm going to close this issue. If you still have questions feel free to reopen it!
