### ISSUE TITLE
Get some stack safety for task similar to fp-ts

### ISSUE THREAD

**Issue by baetheus** [nullpub/fun#24]
See https://github.com/gcanti/fp-ts/pull/1591/files

**Comment by pixeleet** [comment]
Porting this test to Task passes, e.g.
```ts
Deno.test('stack-safety', async () => {
  const range = (n: number) => pipe(new Array(n).map((_, idx) => idx + 1))
  const doProcessing = (number: number) => T.of(number * 2)
  const pipeline = pipe(T.of(range(55000)), T.chain(A.traverse(T.Applicative)(doProcessing)))

  const res = await pipeline()

  assertEquals(res.length, 55000)
})
```

Is there any reason we're not stack-safe already?

**Comment by baetheus** [comment]
I think this was resolved in main but hasn't been pushed to a versioned label yet.

**Comment by pixeleet** [comment]
I'll close the issue, I did hit you up on functional programming slack for easier communication. 
Ping me if you have a moment ;)

**Comment by pixeleet** [comment]
> I'll close the issue, I did hit you up on functional programming slack for easier communication. Ping me if you have a moment ;)

Nvm, can't close it, do please close then.
