### ISSUE TITLE
Add sequence functions to Array, Option, Either modules

### ISSUE THREAD

**Issue by noverby** [nullpub/fun#7]
There are no convenience sequence functions like in `fp-ts` for doing: 
* `Option<T>[]` -> `Option<T[]>`
* `Either<E,T>[]` -> `Either<E,T[]>`

**Comment by baetheus** [comment]
This was a decision made early on when working out the type classes in hkts. You can see a discussion on it [here](https://github.com/nullpub/hkts/issues/3). You can create a sequence function for any ADT with an Applicative class by doing this:

```
import * as A from "https://deno.land/x/fun/array.ts";
import * as O from "https://deno.land/x/fun/option.ts";
import { identity, pipe } from "https://deno.land/x/fun/fns.ts";

const sequence = pipe(
  O.map(identity),
  A.traverse(O.Applicative)
)

console.log(sequence([O.some(1), O.some(2)])) // { tag: "Some", value: [ 1, 2 ] }
console.log(sequence([O.none, O.some(2)])) // { tag: "None" }
```

I have two reasons for not creating a sequence function for each adt.

1. It's trivial to create that behavior from Array's traverse export.
2. I want to keep cross module imports low (ie. not pulling in all of the array.ts file for people that only want option or either).

I hope that previous issue link and the above code work for you!

**Comment by baetheus** [comment]
After playing around with the traverse function for awhile I found that the generic is not inferred properly by TypeScript still in the above example. I've implemented a `createSequence` function that coerces to the correct type in PR #8. Perhaps you wouldn't mind reviewing that?
